"""fix delivery model

Revision ID: 02c9e158f72c
Revises: 16e7af270ca3
Create Date: 2024-08-09 14:07:43.393271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c9e158f72c'
down_revision: Union[str, None] = '16e7af270ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baskets', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'baskets', 'clients', ['client_id'], ['id'])
    op.alter_column('coupons', 'discount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('favorites', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('favorites', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('favorites', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'favorites', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'favorites', 'clients', ['client_id'], ['id'])
    op.alter_column('orders', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('orders', 'amount_of_delivery',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('virtual_account', 'balance',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('virtual_account', 'up_balance',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('virtual_account', 'up_balance',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('virtual_account', 'balance',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('orders', 'amount_of_delivery',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('orders', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'client_id')
    op.drop_column('favorites', 'product_id')
    op.drop_column('favorites', 'company_id')
    op.alter_column('coupons', 'discount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'baskets', type_='foreignkey')
    op.drop_column('baskets', 'client_id')
    # ### end Alembic commands ###
