"""added client in prize and ticket model

Revision ID: 0cdf8fc99c74
Revises: e7aa67048c3a
Create Date: 2024-05-20 23:01:48.654281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cdf8fc99c74'
down_revision: Union[str, None] = 'e7aa67048c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupons', 'discount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('prizes', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prizes', 'clients', ['client_id'], ['id'])
    op.add_column('tickets', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'client_id')
    op.drop_constraint(None, 'prizes', type_='foreignkey')
    op.drop_column('prizes', 'client_id')
    op.alter_column('coupons', 'discount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
