"""create join task

Revision ID: 431c68a364c1
Revises: 5ff5d162e2c5
Create Date: 2024-06-10 17:42:40.106002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431c68a364c1'
down_revision: Union[str, None] = '5ff5d162e2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_tasks', sa.Column('quantity', sa.String(), nullable=True))
    op.add_column('client_tasks', sa.Column('done', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('quantity', sa.String(length=200), nullable=True))
    op.alter_column('coupons', 'discount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('tasks', sa.Column('type', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'quantity')
    op.drop_column('tasks', 'type')
    op.alter_column('coupons', 'discount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'client_tasks', type_='foreignkey')
    op.drop_column('client_tasks', 'done')
    op.drop_column('client_tasks', 'quantity')
    # ### end Alembic commands ###
