"""edit tickets and added relationship for tickets clients and company

Revision ID: 696f5b80640f
Revises: a729230e05d1
Create Date: 2024-05-21 09:47:51.828490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696f5b80640f'
down_revision: Union[str, None] = 'a729230e05d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'client_id')
    )
    op.alter_column('coupons', 'discount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('tasks', sa.Column('short_description', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('reward_type', sa.String(length=200), nullable=True))
    op.add_column('tasks', sa.Column('reward', sa.String(length=200), nullable=True))
    op.add_column('tasks', sa.Column('date_end', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('status', sa.String(length=200), nullable=True))
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.create_foreign_key(None, 'tasks', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'company_id')
    op.drop_column('tasks', 'date_end')
    op.drop_column('tasks', 'reward')
    op.drop_column('tasks', 'reward_type')
    op.drop_column('tasks', 'short_description')
    op.alter_column('coupons', 'discount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_table('client_tasks')
    # ### end Alembic commands ###
