"""added color and quantity_ticket in Competition

Revision ID: a729230e05d1
Revises: d201062bde64
Create Date: 2024-05-21 08:30:51.680800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a729230e05d1'
down_revision: Union[str, None] = 'd201062bde64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('color', sa.String(), nullable=True))
    op.add_column('competitions', sa.Column('quantity_ticket', sa.Integer(), nullable=True))
    op.alter_column('coupons', 'discount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupons', 'discount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('competitions', 'quantity_ticket')
    op.drop_column('competitions', 'color')
    # ### end Alembic commands ###
