"""added field for client

Revision ID: ac1b39a1d4e5
Revises: d60aa8423c83
Create Date: 2024-06-07 11:00:59.957762

"""
from typing import Sequence, Union

import fastapi_storages
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1b39a1d4e5'
down_revision: Union[str, None] = 'd60aa8423c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('photo', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.alter_column('coupons', 'discount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupons', 'discount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('clients', 'date_of_birth')
    op.drop_column('clients', 'gender')
    op.drop_column('clients', 'photo')
    # ### end Alembic commands ###
