"""update field company

Revision ID: d60aa8423c83
Revises: 652bf9c8dc9c
Create Date: 2024-05-31 14:24:02.664545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd60aa8423c83'
down_revision: Union[str, None] = '652bf9c8dc9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('max_pay_point_company', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('cashback_company', sa.String(), nullable=True))
    op.alter_column('coupons', 'discount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupons', 'discount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('companies', 'cashback_company')
    op.drop_column('companies', 'max_pay_point_company')
    # ### end Alembic commands ###
