"""added relation TransactionCompetition and Client

Revision ID: eb93904942f4
Revises: abf13d03d497
Create Date: 2024-06-18 07:05:00.083400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb93904942f4'
down_revision: Union[str, None] = 'abf13d03d497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupons', 'discount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('tasks', 'reward',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Integer(),
               postgresql_using="reward::integer",
               existing_nullable=True)
    op.add_column('transaction_competitions', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction_competitions', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_competitions', type_='foreignkey')
    op.drop_column('transaction_competitions', 'client_id')
    op.alter_column('tasks', 'reward',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('coupons', 'discount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
