"""added new field in company

Revision ID: f7895ee7f969
Revises: 3e58d47777b8
Create Date: 2024-05-24 19:46:47.165125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7895ee7f969'
down_revision: Union[str, None] = '3e58d47777b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('ALTER TABLE companies ALTER COLUMN max_pay_point TYPE JSON USING max_pay_point::JSON')
    op.execute('ALTER TABLE companies ALTER COLUMN cashback TYPE JSON USING cashback::JSON')

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('another_photo', sa.JSON(), nullable=True))
    op.alter_column('companies', 'max_pay_point',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    op.alter_column('companies', 'cashback',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('coupons', 'discount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupons', 'discount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('companies', 'cashback',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('companies', 'max_pay_point',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('companies', 'another_photo')
    # ### end Alembic commands ###
