name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy code to server
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GIT_USER: ${{ github.actor }}
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /var/www/site
          git config --global credential.helper store
          GIT_USER="viqto"
#          GH_TOKEN="token"
          echo "https://${GIT_USER}:${GH_TOKEN}@github.com" > ~/.git-credentials
          cat ~/.git-credentials
          git pull
          supervisorctl restart fastapi
        EOF
