name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Print environment variables for debugging
      run: |
        echo "Server User: ${{ secrets.SERVER_USER }}"
        echo "Server IP: ${{ secrets.SERVER_IP }}"
        echo "GitHub Actor: ${{ github.actor }}"

    - name: Deploy code to server
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GIT_USER: ${{ github.actor }}
      run: |
        echo "Starting SSH connection to the server"
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          echo "Connected to server"
          cd /var/www/site || exit
          echo "Changed directory to /var/www/site"
          git config --global credential.helper store
          echo "Configured git credential helper"
          echo "https://${GIT_USER}:${GH_TOKEN}@github.com" > ~/.git-credentials
          echo "Stored GitHub credentials"
          git pull || exit
          echo "Pulled latest code from GitHub"
          supervisorctl restart fastapi || exit
          echo "Restarted fastapi"
        EOF
        echo "Deployment script completed"
